version: '3.4'

services:
  milionandup.api.property:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  millionandup.api.propertyimages:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"


  millionandup.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - milionandup.api.property
    ports:
      - "6107:80"


  millionandup.authserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6108:80"

